// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8j5E4e1d9F-2pXm76-s8q6nPBQa-R0Q',
    appId: '1:186276145652:web:325c3eb552e6decee0b1a1',
    messagingSenderId: '186276145652',
    projectId: 'ecommerce-app-15c08',
    authDomain: 'ecommerce-app-15c08.firebaseapp.com',
    storageBucket: 'ecommerce-app-15c08.appspot.com',
    measurementId: 'G-6NWTLZNB4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lWu8luht48VYdDSuvF-din2oP2QXRik',
    appId: '1:186276145652:android:486584169b59957be0b1a1',
    messagingSenderId: '186276145652',
    projectId: 'ecommerce-app-15c08',
    storageBucket: 'ecommerce-app-15c08.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyB1Br0woLGswrwd9qu-sCI2UAw52i6_4nE",
      authDomain: "ecommerce-app-729a2.firebaseapp.com",
      projectId: "ecommerce-app-729a2",
      storageBucket: "ecommerce-app-729a2.appspot.com",
      messagingSenderId: "518165598235",
      appId: "1:518165598235:web:89a00a7a9df308db6928be",
      measurementId: "G-PVQB87B77X");
}
